version: '3.2'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    entrypoint: ./entrypoint.sh
    volumes:
      - ./devops_app:/app/devops_app
    ports:
      - "5001:5001"

#  mongo:
#    image: mongo:latest
#    volumes:
#      - ./db_volume:/data/db
#    ports:
#      - "27017:27017"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8443:80"
    volumes:
      - ./certs/:/etc/nginx/certs
